#version: '3'

services:
  node-app:
    build: .
    image: node-app
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    #ports:
    #- '3000:3000'
    depends_on:
      - mongodb
    # volumes:
    # - .:/usr/src/node-app
    volumes:
      - /mnt/volume_tor1_01/app/uploads:/usr/src/node-app/uploads
      - /mnt/volume_tor1_01/app/logs:/usr/src/node-app/logs
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - /mnt/volume_tor1_01/mongodb:/data/db
    networks:
      - node-network

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - node-network
    depends_on:
      - node-app

volumes:
  dbdata:
  caddy_data:
  caddy_config:

networks:
  node-network:
    driver: bridge
