const allRoles = {
  member: ['getUsers', 'addPurchaseOrders', 'getPurchaseOrders', 'getVendors'],
  lead: [
    'getUsers',
    'getCustomers',
    'manageCustomers',
    'manageVendors',
    'getVendors',
    'deletePurchaseOrders',
    'addPurchaseOrders',
    'getPurchaseOrders',
    'updatePurchaseOrders',
    'getChecklists',
    'getJobTypes',
  ],
  owner: [
    'getUsers',
    'manageUsers',
    'getCustomers',
    'manageCustomers',
    'manageVendors',
    'getVendors',
    'approvePurchaseOrders',
    'deletePurchaseOrders',
    'addPurchaseOrders',
    'getPurchaseOrders',
    'updatePurchaseOrders',
    'getTenant',
    'manageTenant',
    'manageChecklists',
    'getChecklists',
    'manageJobTypes',
    'getJobTypes',
  ],
  admin: [
    'getUsers',
    'manageUsers',
    'getCustomers',
    'manageCustomers',
    'manageVendors',
    'getVendors',
    'approvePurchaseOrders',
    'deletePurchaseOrders',
    'addPurchaseOrders',
    'getPurchaseOrders',
    'updatePurchaseOrders',
    'getTenant',
    'manageTenant',
    'manageChecklists',
    'getChecklists',
  ],
};

const roles = Object.keys(allRoles);
const roleRights = new Map(Object.entries(allRoles));

module.exports = {
  roles,
  roleRights,
};
